// <auto-generated />
using AcademicInfoServer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace AcademicInfoServer.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20190115220201_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AcademicInfoServer.Models.Admin", b =>
                {
                    b.Property<string>("Username")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Adresa")
                        .IsRequired();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("NumarTelefon")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Nume")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("Prenume")
                        .IsRequired();

                    b.Property<string>("Salt")
                        .IsRequired();

                    b.Property<int>("UserType");

                    b.HasKey("Username");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("AcademicInfoServer.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("FacultyId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("AcademicInfoServer.Models.Discipline", b =>
                {
                    b.Property<string>("Cod")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("An");

                    b.Property<int>("Credite");

                    b.Property<string>("Nume")
                        .IsRequired();

                    b.Property<int>("Semestru");

                    b.Property<int>("SpecializareId");

                    b.Property<string>("TeacherUsername");

                    b.Property<int>("Type");

                    b.HasKey("Cod");

                    b.HasIndex("SpecializareId");

                    b.HasIndex("TeacherUsername");

                    b.ToTable("Discipline");
                });

            modelBuilder.Entity("AcademicInfoServer.Models.Faculty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Adresa")
                        .IsRequired();

                    b.Property<string>("Nume")
                        .IsRequired();

                    b.Property<string>("NumeUniveristate")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Faculty");
                });

            modelBuilder.Entity("AcademicInfoServer.Models.FacultyEnroll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("GroupId")
                        .IsRequired();

                    b.Property<int>("SpecializareId");

                    b.Property<string>("StudentUsername");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("SpecializareId");

                    b.HasIndex("StudentUsername");

                    b.ToTable("FacultyEnroll");
                });

            modelBuilder.Entity("AcademicInfoServer.Models.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DataNotei");

                    b.Property<double>("GradeValue");

                    b.Property<int?>("GradesToDisciplineId");

                    b.Property<double>("ProcentInnerType");

                    b.Property<double>("ProcentOuter");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("GradesToDisciplineId");

                    b.ToTable("Grade");
                });

            modelBuilder.Entity("AcademicInfoServer.Models.GradesToDiscipline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DisciplineCod")
                        .IsRequired();

                    b.Property<string>("StudentUsername");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineCod");

                    b.HasIndex("StudentUsername");

                    b.ToTable("GradeToDiscipline");
                });

            modelBuilder.Entity("AcademicInfoServer.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("GroupName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Group");
                });

            modelBuilder.Entity("AcademicInfoServer.Models.Specializare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AdminUsername");

                    b.Property<bool>("CuFrecventa");

                    b.Property<int?>("DepartmentId");

                    b.Property<string>("DepartmentName")
                        .IsRequired();

                    b.Property<int>("Limba");

                    b.Property<int>("NumarSemestre");

                    b.Property<string>("Nume")
                        .IsRequired();

                    b.Property<double>("TaxaPerCredit");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("AdminUsername");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Specializare");
                });

            modelBuilder.Entity("AcademicInfoServer.Models.Student", b =>
                {
                    b.Property<string>("Username")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("An")
                        .IsRequired();

                    b.Property<string>("CNP")
                        .IsRequired();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Generatie")
                        .IsRequired();

                    b.Property<string>("InitialaParinte")
                        .IsRequired();

                    b.Property<int>("NumarMatricol");

                    b.Property<string>("NumarTelefon")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Nume")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("Prenume")
                        .IsRequired();

                    b.Property<string>("Salt")
                        .IsRequired();

                    b.Property<int>("UserType");

                    b.HasKey("Username");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("AcademicInfoServer.Models.Teacher", b =>
                {
                    b.Property<string>("Username")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("NumarTelefon")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Nume")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("Prenume")
                        .IsRequired();

                    b.Property<string>("Salt")
                        .IsRequired();

                    b.Property<int>("UserType");

                    b.HasKey("Username");

                    b.ToTable("Teacher");
                });

            modelBuilder.Entity("AcademicInfoServer.Models.Department", b =>
                {
                    b.HasOne("AcademicInfoServer.Models.Faculty")
                        .WithMany("Departments")
                        .HasForeignKey("FacultyId");
                });

            modelBuilder.Entity("AcademicInfoServer.Models.Discipline", b =>
                {
                    b.HasOne("AcademicInfoServer.Models.Specializare", "Specializare")
                        .WithMany()
                        .HasForeignKey("SpecializareId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AcademicInfoServer.Models.Teacher")
                        .WithMany("DisciplinesHolded")
                        .HasForeignKey("TeacherUsername");
                });

            modelBuilder.Entity("AcademicInfoServer.Models.FacultyEnroll", b =>
                {
                    b.HasOne("AcademicInfoServer.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AcademicInfoServer.Models.Specializare", "Specializare")
                        .WithMany()
                        .HasForeignKey("SpecializareId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AcademicInfoServer.Models.Student")
                        .WithMany("FacultiesEnrolled")
                        .HasForeignKey("StudentUsername");
                });

            modelBuilder.Entity("AcademicInfoServer.Models.Grade", b =>
                {
                    b.HasOne("AcademicInfoServer.Models.GradesToDiscipline")
                        .WithMany("Grades")
                        .HasForeignKey("GradesToDisciplineId");
                });

            modelBuilder.Entity("AcademicInfoServer.Models.GradesToDiscipline", b =>
                {
                    b.HasOne("AcademicInfoServer.Models.Discipline", "Discipline")
                        .WithMany()
                        .HasForeignKey("DisciplineCod")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AcademicInfoServer.Models.Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentUsername");
                });

            modelBuilder.Entity("AcademicInfoServer.Models.Specializare", b =>
                {
                    b.HasOne("AcademicInfoServer.Models.Admin")
                        .WithMany("Specializares")
                        .HasForeignKey("AdminUsername");

                    b.HasOne("AcademicInfoServer.Models.Department")
                        .WithMany("Specializares")
                        .HasForeignKey("DepartmentId");
                });
#pragma warning restore 612, 618
        }
    }
}
